version: "3.9"

services:

  backend:
    image: 2023bcs0005anush/2023_batch_2_2023bcs0005_backend
    container_name: backend_anush_2023BCS0005
    ports:
      - "8082:5000"

  frontend:
    image: 2023bcs0005anush/2023_batch_2_2023bcs0005_frontend
    container_name: frontend_anush_2023BCS0005
    ports:
      - "8081:80"
    depends_on:
      - backend
